"""
CopilotLens Capital Logic Action Generator
Generates production-ready Java Caplet Action boilerplate (subclassing AbstractAction),
parameter mapping, config.xml action definitions, and JUnit component test scaffolds.
"""

from pathlib import Path
from typing import Dict, Any


class LogicActionGenerator:
    """Generates Java Caplet Action classes and XML configurations for Capital Logic."""

    def __init__(self, repo_path: str):
        self.repo_path = Path(repo_path)

    def generate_action(self, action_name: str, target_object: str = "DEVICE_CONNECTOR", package_name: str = "chs.caplets.logic.actions") -> Dict[str, Any]:
        """
        Generates Java action class, config.xml snippet, and JUnit test scaffold.
        """
        clean_name = action_name.replace("Action", "").replace(" ", "")
        class_name = f"{clean_name}Action"
        test_class_name = f"{class_name}Test"

        # 1. Java Action Class Content
        java_code = f"""package {package_name};

import chs.caf.cafmain.actions.AbstractAction;
import chs.cof.parts.IXObject;
import chs.cof.parts.IXDesign;
import java.util.Collection;

/**
 * Capital Logic Action: {class_name}
 * Target Domain Object: {target_object}
 * Generated by CoPilotLens Action Generator.
 */
public class {class_name} extends AbstractAction {{

    private String targetObjectId;

    public {class_name}() {{
        super("{class_name}");
    }}

    @Override
    public boolean prepare() {{
        // Validation logic before action execution
        return getContext() != null;
    }}

    @Override
    public void execute() throws Exception {{
        IXDesign activeDesign = (IXDesign) getContext().getDesign();
        if (activeDesign == null) {{
            throw new IllegalStateException("No active design found in context.");
        }}

        // Transactional execution on {target_object}
        System.out.println("[CoPilotLens Action] Executing {class_name} on target: " + target_object);
    }}

    @Override
    public boolean isUndoable() {{
        return true;
    }}

    public void setTargetObjectId(String targetObjectId) {{
        this.targetObjectId = targetObjectId;
    }}

    public String getTargetObjectId() {{
        return targetObjectId;
    }}
}}
"""

        # 2. Config XML snippet
        xml_config = f"""<!-- Capital Caplet Action Definition for {class_name} -->
<action id="{class_name}" class="{package_name}.{class_name}" target="{target_object}">
  <parameter name="targetObjectId" type="String" required="true"/>
  <description>Executes {clean_name} operation on {target_object} objects.</description>
</action>
"""

        # 3. JUnit Component Test Scaffold
        junit_test_code = f"""package {package_name};

import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 * Component Test for {class_name}.
 */
public class {test_class_name} {{

    private {class_name} action;

    @Before
    public void setUp() {{
        action = new {class_name}();
    }}

    @Test
    public void testPrepare() {{
        assertNotNull("Action instance should not be null", action);
    }}

    @Test
    public void testIsUndoable() {{
        assertTrue("Action should be undoable", action.isUndoable());
    }}
}}
"""

        return {
            "action_class_name": class_name,
            "target_object": target_object,
            "package_name": package_name,
            "java_action_code": java_code,
            "xml_config_snippet": xml_config,
            "junit_test_code": junit_test_code
        }
